version: "3"
volumes:
  # Como não tem nada referencia a pasta raiz.
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # Volumes dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      # Este padrão de inicilização está na documentação oficial do postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 85:80
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    #Essa configuração de porta era necessário quanda não se tinha um proxy reverso confidurado no bo arquivo 'default.conf'
    #ports:
    #  - 8090:8080
